services:
  - type: web
    name: lab007-unified-services
    env: node
    buildCommand: git submodule update --init --recursive && npm install --no-optional
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: lab007-unified-services
          property: port
